### ISSUE TITLE
M600 Filament Change Unload/Load Length

### ISSUE THREAD

**Issue by bgcgenom** [wabbitguy/Kobra_Plus#3] opened 2023-09-10 16:24 UTC
First off, thank you for putting this together.  I have worked on getting this done myself but haven't quite figured out how to get the BOARD_AC_TRI_F1_V1 in the Marlin update to make my own build.

Anyways.  I installed this firmware and it works great!  But, there is one issue for the Kobra Plus.  In the Configuration_adv.h file, line 2162 and 2171, FILAMENT_CHANGE_UNLOAD_LENGTH and FILAMENT_CHANGE_FAST_LOAD_LENGTH seem to need adjustment.  Measuring from the back of the extruder teeth where the filament first enters to the top of the hot end is 390mm.  This makes M600 filament changes difficult because it will not extract all the filament on its own.  Another side effect is that when inserting the new filament, it doesn't load far enough in and doesn't make it to the hot end prior to the purge of 80mm.  Only about 3 or 4 mm is remaining to purge out the previous color.  I know the math there doesn't work out.

As mentioned before, I would build this to tinker with the exact numbers but I just can't get the board entered into the build correctly.

Thanks again for your hard work!  Cheers!

**Comment by wabbitguy** [comment] 2023-09-10 18:17
@bgcgenom first have to thank you for going to the length of actually measuring the distance. From the top of the hot end (PTFE fitting) to the nozzle is roughly 90mm..so we've 480mm for a full unload.

For the load in, part of the problem is everyone loads in the new filament in a completely different way. Some will just get it to the extruder gears, others will shove it 50 to 100mm into the Bowden tube after the gears. This cause grinding of the filament (quite badly in some cases). The settings load in 350mm and then another 80mm of purge. Which according to your measurement is going to be short.

I am closing this issue but you can still leave comments to me here with results to how you find it working or what needs adjusting. Once ironed out, I'll update the main repository for the PLUS users.

The firmware is adjusted according to your measurements. Download and install.

[firmware.bin.zip](https://github.com/wabbitguy/Kobra_Plus/files/12569857/firmware.bin.zip)

Re the board and the build, you need to use KeilARM compiler to make your own builds. There's a Reddit page on how it's all done, sort of a step by step. If you're used to the usual gamut of compilers like Platform I/O, Arduino, VS code, Keil is a LONG way from them, goofy syntax and all.

Mel

**Closed as completed by wabbitguy** 2023-09-10 18:17 UTC

**Comment by bgcgenom** [comment] 2023-09-11 07:40
Wonderful!  Thanks for the recompile.  That will get me started on the path I was hoping for.  I really appreciate you pointing me in the right direction.  Frankly it was getting a bit frustrating, I almost jumped ship to work on Klipper.  Though that may still be in the future.

**Comment by bgcgenom** [comment] 2023-09-16 19:27
That worked perfectly!  Thank you so very much!  Also, you defiantly got me on the right path with Keil uVision.  I am now able to compile the firmware.  You rock!

**Comment by wabbitguy** [comment] 2023-09-16 22:37
@bgcgenom awesome to hear it's working for you. Plus the fact you can now beat the beast into submission with Keil.

Have fun and PRINT ON!...LOL

Mel
---
